### ISSUE TITLE
Cannot extract with 7zip in latest spring-launcher

### ISSUE THREAD

**Issue by gajop** [gajop/spring-launcher#115]
Works in a2c35d1 , doesn't work in 6455f7b. 
My guess is dependency updates broke it (maybe related: @p2004a )

(Don't upgrade BAR to latest spring-launcher @Beherith )

Will investigate and see if I can fix without reverting...

**Comment by Beherith** [comment]
Ty for the heads up!

**Comment by p2004a** [comment]
I've merged already master here to one in bar. Sorry :/ will also investigate, maybe I accidentally missed some breaking change when updating deps..

**Comment by gajop** [comment]
Not a problem! I ended up doing https://github.com/gajop/spring-launcher/commit/8368868c542b473b5ed97aae87d73c99f4e3e52d , had to revert 7zip but I think that's acceptable.
Feel free to make a PR updating 7zip separately if you want. 

(@Beherith I *think* this should work, but let me test it with SB first a bit more)

**Comment by gajop** [comment]
Ok it's a "works for me now". Let me know if you experience any issues
