### ISSUE TITLE
Portable launcher should assume that it already has the engine and not try to download it

### ISSUE THREAD

**Issue by ForbodingAngel** [gajop/spring-launcher#19]
The current method is a setup for failure that is tied to an arbitrary "has it been deleted yet?" spring build deletion cycle.

The entire point of portable is to be self contained insomuch that is has the base game and engine distributed with it (ignoring the fact that checking for game/luamenu updates happen upon launch <- this is to be expected). So it doesn't make sense for the launcher to fail because it's checking for an engine build it already has.

Portable shouldn't be trying to download the engine at all. If you are using the portable build then it is clear and should be obvious that that comes with maintenance responsibilities.

**Comment by gajop** [comment]
If you don't want it to download the engine, then just remove the engine from the list of downloads for the portable build: https://github.com/EvolutionRTS/EvoRTS-Chobby/blob/master/dist_cfg/config.json#L40 ?

This doesn't merit an issue - unlike your original problem ("launcher tries to download something that already exists"), which is worth fixing

**Comment by ForbodingAngel** [comment]
So in other words:

This is already doable. All you have to do is remove the engine from the downloads list in your game's chobby repo in dist_cfg/config.json

Awesome, thanks for the info :-)
