### ISSUE TITLE
Re: Portable launcher should assume that it already has the engine and not try to download it

### ISSUE THREAD

**Issue by ForbodingAngel** [gajop/spring-launcher#20]
Since I can't comment and re-open the issue...

Related to this:
https://github.com/gajop/spring-launcher/issues/19

Removing the engine from the list of downloads results in it not launching chobby at all with a predictable error:
http://logs.springrts.com/logfiles/141/

Which brings me back to my original request of:
The current method is a setup for failure that is tied to an arbitrary "has it been deleted yet?" spring build deletion cycle.

The entire point of portable is to be self contained insomuch that is has the base game and engine distributed with it (ignoring the fact that checking for game/luamenu updates happen upon launch <- this is to be expected). So it doesn't make sense for the launcher to fail because it's checking for an engine build it already has.

Portable shouldn't be trying to download the engine at all. If you are using the portable build then it is clear and should be obvious that that comes with maintenance responsibilities.

********

With the added caveat that I should be able to tell chobby launcher what engine version it is to use without it trying to download it.

**Comment by ForbodingAngel** [comment]
Ok so I merged the PR and grabbed the new launcher version. Unfortunately it still seems to fail upon clicking "Start"

http://logs.springrts.com/logfiles/146/

**Comment by gajop** [comment]
As discussed in chat, I'm not convinced you actually have an engine in that location (you need to put it yourself now that you don't want it to be downloaded)
