### ISSUE TITLE
IceXuick: New installer needs admin rights or you get UAC error...

### ISSUE THREAD

**Issue by gajop** [gajop/spring-launcher#23]

**Comment by silentwings** [comment]
i guess that's a necessary consequence of wanting to install to a user specified location

**Comment by gajop** [comment]
@ IceXuick:
I'd like to know more, mainly: 
- Are you installing for all users or just yourself? Installing for yourself generally shouldn't require admin rights
- Where did you install?
- Is it an update or a fresh install that's causing the problem?
- How does the error look like? (Screenshot please)

**Comment by gajop** [comment]
Never got feedback
