### ISSUE TITLE
Failing downloads proceed to next step as if it was successful

### ISSUE THREAD

**Issue by gajop** [gajop/spring-launcher#32]

**Comment by gajop** [comment]
Example log: http://logs.springrts.com/logfiles/212/

**Comment by abma** [comment]
very likely this is because pr-downloader set an exit code of 0:

this should be fixed by
https://github.com/spring/pr-downloader/commit/d3e5a4ad888a82a43c6ab3997c41992a05fd1764

**Comment by gajop** [comment]
@abma I'd like to use an upgraded version of pr-downloader when binaries become available. I'm now mainly using them when they get built with spring builds.

**Comment by abma** [comment]
oops, updated it a few minutes ago. new (develop-)builds should be available soon.

**Comment by gajop** [comment]
thanks, i've merged this functionality to maintenance too as it was actually happening with in-game downloader functionality
