### ISSUE TITLE
evorts uses old version of pr-downloader

### ISSUE THREAD

**Issue by abma** [gajop/spring-launcher#35]
i.e. http://logs.springrts.com/logfiles/234/

"pr-downloader 0.7-524-g8eab580"

where to to file a bug about this?

**Comment by gajop** [comment]
1) if I need to update the one provided by spring-launcher then here
2) if this one is latest, it means evorts should update to latest launcher (requires manual intervention). that'd be done here: https://github.com/EvolutionRTS/EvoRTS-Chobby

**Comment by gajop** [comment]
and here's how 2 is done normally

**Comment by gajop** [comment]
I think this has been resolved
