### ISSUE TITLE
user's app-update.yml cannot be found for some reason?

### ISSUE THREAD

**Issue by gajop** [gajop/spring-launcher#54]
http://logs.springrts.com/logfiles/568/

**Comment by azaremoth** [comment]
Same thing here:
[http://logs.springrts.com/logfiles/2541/](url)

Shouldn't a "isolation" tag get rid of such stuff? At least the name sounds that way.

**Comment by azaremoth** [comment]
app-update.yml does also not exist in the respective folder. 

Content of ...\resources is:
app.asar.unpacked
app.asar
elevate.exe

What does it do? The game downloads as intended, but you can not automatically start it. After deselecting "Check for updates" everything runs smoothly. Still - users will be puzzeled with this. Is there a way to just ignor the error message?

**Comment by gajop** [comment]
This is caused by the launcher update mechanism failing in a bizarre way, I'm not sure what the exact issue is.

> Is there a way to just ignor the error message?

This is exactly what the launcher should do, I'll implement that next.
