### ISSUE TITLE
After a download failure, the zip files that it half-downloaded are kept open

### ISSUE THREAD

**Issue by Beherith** [gajop/spring-launcher#81]
After a failed update, if you check and uncheck the check for updates checkbox, then the update button becomes active again. If you press the update button then, it will 100% fail because some files were left open by previous attempt at updating: 

http://logs.springrts.com/logfiles/2405/

**Comment by Beherith** [comment]
Another: http://logs.springrts.com/logfiles/2488/

**Comment by gajop** [comment]
I think you are misdiagnosing this. Files aren't kept open after the failure, temporary files are deleted after download finishes, so once you redo the download, they just happen to have the same name.
The cause of failure is attributed to some third party software (antivirus?) that's keeping these files opened after download has finished, and is therefore causing the unzip program to have issues unzipping them.

The solution here should be to keep trying to unzip a few times (e.g. 5 times with 3s gaps between?), so as to let the antivirus software finish its scan before handling the files
