### ISSUE TITLE
use https://logs.springrts.com

### ISSUE THREAD

**Issue by abma** [gajop/spring-launcher#87]
currently http is used: can this be easily changed to https as uploads possible contain sensitive data?

i guess https://github.com/gajop/spring-launcher/blob/27404a93f9a4d965cba815255ac391830fb6976f/src/log_uploader.js#L57 needs to be changed to https?

**Comment by gajop** [comment]
Electron's builtin `net` module was giving me some trouble so I thought it was a backend/cert issue, but it seems to work now with a diffent lib

**Comment by gajop** [comment]
PS: Maybe wait a bit before you enforce https on the backend, as not all clients get this update immediately
